version: "3.8"
services:
    php-apache:
        image: php:8.0-apache
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./src/api:/var/www/html
        ports:
            - 8080:80
    db:
        image: mysql/mysql-server:8.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test_db
            MYSQL_USER: fs
            MYSQL_PASSWORD: pass
        volumes:
            - ./db/fixtures:/docker-entrypoint-initdb.d/
            - ./db/conf:/etc/mysql/conf.d
        ports:
            - 3306:3306
