export let orchestra = [
    { name: "firstFlute", max: 1, selected: 0 },
    { name: "secondFlute", max: 1, selected: 0 },
    { name: "firstOboe", max: 1, selected: 0 },
    { name: "secondOboe", max: 1, selected: 0 },
    { name: "firstClarinet", max: 1, selected: 0 },
    { name: "secondClarinet", max: 1, selected: 0 },
    { name: "saxophone", max: 1, selected: 0 },
    { name: "bassoon", max: 2, selected: 0 },
    { name: "frenchHorn", max: 2, selected: 0 },
    { name: "trumpet", max: 1, selected: 0 },
    { name: "trombone", max: 1, selected: 0 },
    { name: "timpani", max: 1, selected: 0 },
    { name: "pitchedPercussion", max: 1, selected: 0 },
    { name: "unpitchedPercussion", max: 1, selected: 0 },
    { name: "pianoCelesta", max: 1, selected: 0 },
    { name: "harp", max: 1, selected: 0 },
    { name: "accordion", max: 1, selected: 0 },
    { name: "electricGuitar", max: 1, selected: 0 },
    { name: "femaleNarrator", max: 1, selected: 0 },
    { name: "maleNarrator", max: 1, selected: 0 },
    { name: "iViolin", max: 6, selected: 0 },
    { name: "iiViolin", max: 5, selected: 0 },
    { name: "viola", max: 4, selected: 0 },
    { name: "violoncello", max: 3, selected: 0 },
    { name: "doublebass", max: 2, selected: 0 },
]
