export let orchestra = [
    { name: "orchestra.firstFlute", max: 1, selected: 0 },
    { name: "orchestra.secondFlute", max: 1, selected: 0 },
    { name: "orchestra.firstOboe", max: 1, selected: 0 },
    { name: "orchestra.secondOboe", max: 1, selected: 0 },
    { name: "orchestra.firstClarinet", max: 1, selected: 0 },
    { name: "orchestra.secondClarinet", max: 1, selected: 0 },
    { name: "orchestra.saxophone", max: 1, selected: 0 },
    { name: "orchestra.bassoon", max: 2, selected: 0 },
    { name: "orchestra.frenchHorn", max: 2, selected: 0 },
    { name: "orchestra.trumpet", max: 1, selected: 0 },
    { name: "orchestra.trombone", max: 1, selected: 0 },
    { name: "orchestra.timpani", max: 1, selected: 0 },
    { name: "orchestra.pitchedPercussion", max: 1, selected: 0 },
    { name: "orchestra.unpitchedPercussion", max: 1, selected: 0 },
    { name: "orchestra.pianoCelesta", max: 1, selected: 0 },
    { name: "orchestra.harp", max: 1, selected: 0 },
    { name: "orchestra.accordion", max: 1, selected: 0 },
    { name: "orchestra.electricGuitar", max: 1, selected: 0 },
    { name: "orchestra.femaleNarrator", max: 1, selected: 0 },
    { name: "orchestra.maleNarrator", max: 1, selected: 0 },
    { name: "orchestra.iViolin", max: 6, selected: 0 },
    { name: "orchestra.iiViolin", max: 5, selected: 0 },
    { name: "orchestra.viola", max: 4, selected: 0 },
    { name: "orchestra.violoncello", max: 3, selected: 0 },
    { name: "orchestra.doublebass", max: 2, selected: 0 },
]